export { UpiPaymentPage } from './UpiPaymentPage'
export { PaymentHistoryPage } from './PaymentHistoryPage'
export { SmartInsightsPage } from './SmartInsightsPage'
export { ScanPayPage } from './ScanPayPage'
export { PayContactsPage } from './PayContactsPage'
export { PayContactScreen } from './PayContactScreen'
export { RequestMoneyPage } from './RequestMoneyPage'
export { BankTransferPage } from './BankTransferPage'
